#pragma once
#ifndef VISUALT_INCLUDE_VISUALT_VERSION_H_
#define VISUALT_INCLUDE_VISUALT_VERSION_H_

#define VISUALT_VERSION_MINOR 2
#define VISUALT_VERSION_MAJOR 3
#define VISUALT_VERSION_PATCH 0
#define VISUALT_VERSION_TWEAK 
#define VISUALT_VERSION "3.2.0"

#endif //VISUALT_INCLUDE_VISUALT_VERSION_H_
