name: Release
on:
  push:
    tags-ignore:
      - 'v*-b'

jobs:
  prerelease:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false